name: nf-core-compomics-workflow
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - flashlfq=1.1.1
  - pandas=0.24.2
  - thermorawfileparser=1.3.4
  - searchgui=4.0.33
  - peptide-shaker=2.0.25
  - unzip=6.0 
  - bioconductor-preprocesscore=1.56.0
  - bioconductor-msnbase=2.20.0
  - r-msqrob=0.7.7
  - r-matrixstats
  
