name: Docker image build and test
# This workflow is triggered on pushes and PRs to the repository.

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  release:
    types: [published]
    branches: [ releases ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      CAPSULE_LOG: none
      WORKFLOW: compomics-pipeline

    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.04.0', '']

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image (dev)
      working-directory: Nextflow/docker
      run: docker build . --file Dockerfile --tag wombatp/${WORKFLOW}:dev

    - name: Install Nextflow
      run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

    - name: Run pipeline with test data
      working-directory: Nextflow
      run: |
          nextflow run main.nf -profile test,docker

    - name: Push Docker image to DockerHub (dev)
      if: ${{ github.event_name == 'push' }}
      run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push wombatp/${WORKFLOW}:dev

    - name: Build Docker image (release)
      working-directory: Nextflow/docker
      if: ${{ github.event_name == 'release' }}
      run: |
          version=${{ github.ref }}
          version=(${version//\// })
          version=${version[2]}
          docker build . --file Dockerfile --tag wombatp/${WORKFLOW}:${version}

  push_dockerhub:
    name: Push new Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Only run if the tests passed
    needs: build
    # Only run for the releases
    if: ${{ github.event_name == 'release' }}
    env:
      WORKFLOW: compomics-pipeline
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
     - name: Check out pipeline code
       uses: actions/checkout@v2

     - name: Build new docker image
       working-directory: Nextflow/docker
       run: docker build --no-cache . -t wombatp/${WORKFLOW}:latest

     - name: Push Docker image to DockerHub (release)
       if: ${{ github.event_name == 'release' }}
       run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          version=${{ github.ref }}
          version=(${version//\// })
          version=${version[2]}
          docker tag wombatp/${WORKFLOW}:latest wombatp/${WORKFLOW}:${version}
          docker push wombatp/${WORKFLOW}:${version}
